//! EU AI Act Article 50 — visible AI disclosure footer for files.
//!
//! When an AI agent writes a document file (.md, .txt, .html, .rst, .csv, .log),
//! a visible disclosure footer is appended so that anyone reading the file
//! knows it was AI-generated. This complements the invisible zero-width
//! watermark applied to chat responses (see `watermark.rs`).
//!
//! The footer includes the agent slug, DID (if available), and a link to
//! the public verification page at ownify.ai/verify-ai.

use std::path::Path;

/// File extensions that are "documents" — text files where a visible footer
/// is safe to append without breaking the format.
const DOCUMENT_EXTENSIONS: &[&str] = &[
    "md", "txt", "rst", "csv", "log", "html", "htm", "markdown", "text",
];

/// Returns true if the file path has a document extension where a visible
/// footer can be safely appended.
pub fn is_document_file(path: &Path) -> bool {
    path.extension()
        .and_then(|ext| ext.to_str())
        .map(|ext| {
            DOCUMENT_EXTENSIONS
                .iter()
                .any(|doc_ext| ext.eq_ignore_ascii_case(doc_ext))
        })
        .unwrap_or(false)
}

/// Build the markdown-style disclosure footer.
///
/// Format:
/// ```text
///
/// ---
/// *Generated by ownify AI agent `slug` · DID: `did:moltrust:xxx` — [Verify](https://ownify.ai/verify-ai)*
/// ```
pub fn disclosure_footer(slug: &str, did: Option<&str>) -> String {
    let did_part = match did {
        Some(d) if !d.is_empty() => format!(" · DID: `{d}`"),
        _ => String::new(),
    };
    let slug_part = if slug.is_empty() { "ownify" } else { slug };
    format!(
        "\n\n---\n*Generated by ownify AI agent `{slug_part}`{did_part} — [Verify at ownify.ai/verify-ai](https://ownify.ai/verify-ai)*\n"
    )
}

/// Build an HTML disclosure footer (for .html files).
pub fn disclosure_footer_html(slug: &str, did: Option<&str>) -> String {
    let did_part = match did {
        Some(d) if !d.is_empty() => format!(" &middot; DID: <code>{d}</code>"),
        _ => String::new(),
    };
    let slug_part = if slug.is_empty() { "ownify" } else { slug };
    format!(
        "\n<hr>\n<p><em>Generated by ownify AI agent <code>{slug_part}</code>{did_part} &mdash; <a href=\"https://ownify.ai/verify-ai\">Verify at ownify.ai/verify-ai</a></em></p>\n"
    )
}

/// Append the appropriate disclosure footer to file content based on the
/// file extension. Returns the content unchanged if the file is not a
/// document type.
pub fn append_disclosure(content: &str, path: &Path, slug: &str, did: Option<&str>) -> String {
    if !is_document_file(path) {
        return content.to_string();
    }

    // Don't double-append if footer already present
    if content.contains("Generated by ownify AI agent") {
        return content.to_string();
    }

    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase())
        .unwrap_or_default();

    if ext == "html" || ext == "htm" {
        format!("{content}{}", disclosure_footer_html(slug, did))
    } else {
        format!("{content}{}", disclosure_footer(slug, did))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_is_document_file_md() {
        assert!(is_document_file(&PathBuf::from("report.md")));
    }

    #[test]
    fn test_is_document_file_txt() {
        assert!(is_document_file(&PathBuf::from("notes.txt")));
    }

    #[test]
    fn test_is_document_file_html() {
        assert!(is_document_file(&PathBuf::from("page.html")));
        assert!(is_document_file(&PathBuf::from("page.htm")));
    }

    #[test]
    fn test_is_document_file_csv() {
        assert!(is_document_file(&PathBuf::from("data.csv")));
    }

    #[test]
    fn test_is_document_file_rst() {
        assert!(is_document_file(&PathBuf::from("doc.rst")));
    }

    #[test]
    fn test_is_document_file_log() {
        assert!(is_document_file(&PathBuf::from("app.log")));
    }

    #[test]
    fn test_is_not_document_file_json() {
        assert!(!is_document_file(&PathBuf::from("config.json")));
    }

    #[test]
    fn test_is_not_document_file_yaml() {
        assert!(!is_document_file(&PathBuf::from("config.yaml")));
    }

    #[test]
    fn test_is_not_document_file_py() {
        assert!(!is_document_file(&PathBuf::from("script.py")));
    }

    #[test]
    fn test_is_not_document_file_rs() {
        assert!(!is_document_file(&PathBuf::from("main.rs")));
    }

    #[test]
    fn test_is_not_document_file_pdf() {
        assert!(!is_document_file(&PathBuf::from("report.pdf")));
    }

    #[test]
    fn test_is_not_document_file_docx() {
        assert!(!is_document_file(&PathBuf::from("report.docx")));
    }

    #[test]
    fn test_is_not_document_file_no_extension() {
        assert!(!is_document_file(&PathBuf::from("README")));
    }

    #[test]
    fn test_disclosure_footer_with_did() {
        let footer = disclosure_footer("ownify-abc123", Some("did:moltrust:abc123"));
        assert!(footer.contains("ownify-abc123"));
        assert!(footer.contains("did:moltrust:abc123"));
        assert!(footer.contains("ownify.ai/verify-ai"));
        assert!(footer.starts_with("\n\n---\n"));
    }

    #[test]
    fn test_disclosure_footer_without_did() {
        let footer = disclosure_footer("ownify-abc123", None);
        assert!(footer.contains("ownify-abc123"));
        assert!(!footer.contains("DID:"));
        assert!(footer.contains("ownify.ai/verify-ai"));
    }

    #[test]
    fn test_disclosure_footer_empty_slug() {
        let footer = disclosure_footer("", Some("did:moltrust:abc"));
        assert!(footer.contains("ownify"));
        assert!(footer.contains("did:moltrust:abc"));
    }

    #[test]
    fn test_disclosure_footer_html_format() {
        let footer = disclosure_footer_html("agent1", Some("did:moltrust:xyz"));
        assert!(footer.contains("<hr>"));
        assert!(footer.contains("agent1"));
        assert!(footer.contains("did:moltrust:xyz"));
        assert!(footer.contains("ownify.ai/verify-ai"));
        assert!(footer.contains("<a href="));
    }

    #[test]
    fn test_append_disclosure_md_file() {
        let content = "# My Report\n\nHello world.";
        let path = PathBuf::from("report.md");
        let result = append_disclosure(content, &path, "agent1", Some("did:moltrust:abc"));
        assert!(result.starts_with("# My Report"));
        assert!(result.contains("---"));
        assert!(result.contains("Generated by ownify AI agent"));
        assert!(result.contains("agent1"));
        assert!(result.contains("did:moltrust:abc"));
    }

    #[test]
    fn test_append_disclosure_html_file() {
        let content = "<html><body><h1>Hello</h1></body></html>";
        let path = PathBuf::from("page.html");
        let result = append_disclosure(content, &path, "agent1", Some("did:moltrust:abc"));
        assert!(result.contains("<hr>"));
        assert!(result.contains("Generated by ownify AI agent"));
        assert!(result.contains("agent1"));
    }

    #[test]
    fn test_append_disclosure_json_file_unchanged() {
        let content = "{\"key\": \"value\"}";
        let path = PathBuf::from("config.json");
        let result = append_disclosure(content, &path, "agent1", Some("did:moltrust:abc"));
        assert_eq!(result, content);
    }

    #[test]
    fn test_append_disclosure_py_file_unchanged() {
        let content = "print('hello')";
        let path = PathBuf::from("script.py");
        let result = append_disclosure(content, &path, "agent1", Some("did:moltrust:abc"));
        assert_eq!(result, content);
    }

    #[test]
    fn test_append_disclosure_no_double_append() {
        let content = "# Report\n\nSome text.\n\n---\n*Generated by ownify AI agent `agent1`*\n";
        let path = PathBuf::from("report.md");
        let result = append_disclosure(content, &path, "agent1", Some("did:moltrust:abc"));
        // Should not append a second footer
        assert_eq!(result, content);
    }

    #[test]
    fn test_append_disclosure_without_did() {
        let content = "# Report\n\nText.";
        let path = PathBuf::from("report.md");
        let result = append_disclosure(content, &path, "agent1", None);
        assert!(result.contains("Generated by ownify AI agent"));
        assert!(result.contains("agent1"));
        assert!(!result.contains("DID:"));
    }

    #[test]
    fn test_append_disclosure_txt_file() {
        let content = "Hello world.";
        let path = PathBuf::from("notes.txt");
        let result = append_disclosure(content, &path, "agent1", None);
        assert!(result.contains("Generated by ownify AI agent"));
        assert!(result.starts_with("Hello world."));
    }

    #[test]
    fn test_append_disclosure_case_insensitive_extension() {
        let content = "Hello";
        let path = PathBuf::from("REPORT.MD");
        let result = append_disclosure(content, &path, "agent1", None);
        assert!(result.contains("Generated by ownify AI agent"));
    }
}